### PR TITLE
 Making the drop down for geometry column to only show geography columns 

### PR DESCRIPTION
**Pull request by hormati**

### CODE REVIEW

**Comment by donmccurdy** [comment]
If the user had a text column containing WKT text (which they hadn't given a geography type in BigQuery for whatever reason), they'd be able to select and use it before this change, but not after. Is that OK? Not sure if it would be common from, say, CSV imports.

**Comment by hormati** [comment]
Is there a good reason that they haven't given it a geography type in BQ?

I think it's best to be strict about these things and enforce the schema as strictly as possible. Otherwise, we will start getting into the business of parsing strings and figuring out what is geography and what is not.

Also, I should note that currently if I select non-geography columns from the drop down, my chrome tab becomes non-responsive.

**Comment by mentin** [comment]
I think the ability to display any text field was useful in original
design, but now we require presence of geography column anyway, when
creating a wrapper query. So it is not very useful, as GeoViz cannot be
used without a typed geography column.

**Comment by donmccurdy** [comment]
OK, sounds good. 👍

**Pull request merged**
